/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    FormBuilder: typeof import('./src/components/FormBuilder.vue')['default']
    IFrameVue: typeof import('./src/components/IFrameVue.vue')['default']
    LayoutView: typeof import('./src/components/LayoutView.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    PrintPassword: typeof import('./src/components/PrintPassword.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VirtualKeyboard: typeof import('./src/components/VirtualKeyboard.vue')['default']
  }
}
