/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    BaseLayout: typeof import('./src/components/BaseLayout.vue')['default']
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    ContactButton: typeof import('./src/components/ContactButton.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    DrawerItem: typeof import('./src/components/DrawerItem.vue')['default']
    Form: typeof import('./src/components/FormBuilder/Form.vue')['default']
    IFrameVue: typeof import('./src/components/IFrameVue.vue')['default']
    LayoutView: typeof import('./src/components/LayoutView.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MenuOptions: typeof import('./src/components/MenuOptions.vue')['default']
    NavigationDrawer: typeof import('./src/components/NavigationDrawer.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    PrintPassword: typeof import('./src/components/PrintPassword.vue')['default']
    RichText: typeof import('./src/components/RichText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleError: typeof import('./src/components/SimpleError.vue')['default']
    View: typeof import('./src/components/View.vue')['default']
    VirtualKeyboard: typeof import('./src/components/VirtualKeyboard.vue')['default']
  }
}
