services:
  node:
    build: .
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - ${APP_PORT-3000}:3000
    networks:
      - app

networks:
  app:
    name: autoatendimento
    external: true
    driver: bridge
