services:
  node:
    build: .
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - ${VITE_APP_PORT-3000}:3000
    networks:
      - app

networks:
  app:
    name: autoatendimento
    driver: bridge
