name: Automation Deploy

on: 
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo
    - run: npm install && npm run build
    - run: git config --global user.email "igor.ribeiro98@outlook.com" && git config --global user.name "Automation"
    - run: cd dist && echo "dominiodoigao" > CNAME && git init && git add -A && git commit -m 'deploy' && git push -f https://IgorRibeiro98:${{ secrets.GITHUB_TOKEN }}@github.com/IgorRibeiro98/landing_page_wrs.git master:gh-pages      
 